# Generated by Django 3.1.4 on 2020-12-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='addnewroom',
            fields=[
                ('rno', models.IntegerField(primary_key=True, serialize=False)),
                ('rtype', models.CharField(max_length=100)),
                ('rprice', models.IntegerField()),
                ('rcondition', models.CharField(max_length=100)),
                ('rstatus', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='checkinmodel',
            fields=[
                ('chno', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('chindate', models.DateField(default='2020-12-15')),
                ('chintime', models.TimeField(default='21:41:04')),
                ('choutdate', models.DateField()),
                ('chouttime', models.TimeField()),
                ('rno', models.IntegerField()),
                ('rtype', models.CharField(max_length=100)),
                ('rprice', models.IntegerField()),
                ('rstatus', models.BooleanField(default=False)),
                ('fullname', models.CharField(max_length=500)),
                ('companyname', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('mobile', models.PositiveIntegerField()),
                ('emailid', models.EmailField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('fulladdress', models.TextField(max_length=500)),
                ('chtotaldays', models.CharField(blank=True, max_length=100)),
                ('person', models.IntegerField(default=0)),
                ('extraperson', models.IntegerField(default=0)),
                ('extrarate', models.IntegerField()),
                ('extradays', models.IntegerField(default=1)),
                ('totalamount', models.FloatField()),
                ('actualamount', models.FloatField(blank=True, null=True)),
                ('finalamount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('roundamount', models.IntegerField(blank=True, null=True)),
                ('advancepaidamount', models.IntegerField(default=0, null=True)),
                ('paybleamount', models.IntegerField(blank=True, null=True)),
                ('roomamount', models.IntegerField(blank=True, default=0)),
                ('gstamount', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=6)),
                ('foodbillamount', models.IntegerField(default=0)),
                ('laundybill', models.IntegerField(default=0)),
                ('phonebill', models.IntegerField(default=0)),
                ('Internetcharge', models.IntegerField(default=0)),
                ('otherchargelable', models.CharField(blank=True, max_length=100)),
                ('othercharge', models.IntegerField(blank=True, default=0, null=True)),
                ('gst', models.FloatField(blank=True, null=True)),
                ('gstshow', models.FloatField(blank=True, null=True)),
                ('discount', models.IntegerField(blank=True, default=0)),
                ('discountamount', models.FloatField(blank=True, null=True)),
                ('paymethod', models.CharField(default='Cash', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='cregister',
            fields=[
                ('registerno', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('fullname', models.CharField(max_length=500)),
                ('companyname', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('mobile', models.PositiveIntegerField()),
                ('emailid', models.EmailField(max_length=200)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('customer_id_type_1', models.CharField(blank=True, max_length=200, null=True)),
                ('proof_id_1', models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d')),
                ('customer_id_type_2', models.CharField(blank=True, max_length=200, null=True)),
                ('proof_id_2', models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d')),
                ('customer_id_type_3', models.CharField(blank=True, max_length=200, null=True)),
                ('proof_id_3', models.ImageField(blank=True, null=True, upload_to='photo/%Y/%m/%d')),
                ('fulladdress', models.TextField(max_length=500)),
                ('in_date', models.DateField(auto_now_add=True)),
                ('in_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='gappconfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appname', models.CharField(blank=True, max_length=200, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('phone', models.IntegerField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('applogo', models.ImageField(blank=True, null=True, upload_to='')),
                ('checkouttime', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='gstmodel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gst', models.DecimalField(decimal_places=1, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.IntegerField()),
                ('actualamount', models.DecimalField(blank=True, decimal_places=4, max_digits=9, null=True)),
                ('roundamount', models.DecimalField(blank=True, decimal_places=1, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='paymentmode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paymethod', models.CharField(default='Cash', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='roomcondition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rcondition', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='roomnumber',
            fields=[
                ('rnumber', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='roomprice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rprice', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='roomtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rtype', models.CharField(max_length=100)),
            ],
        ),
    ]
