# Generated by Django 3.1.4 on 2020-12-15 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghouse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinmodel',
            name='perpersonextrarate',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkinmodel',
            name='chintime',
            field=models.TimeField(default='21:41:47'),
        ),
    ]
