# Generated by Django 3.1.4 on 2020-12-15 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghouse', '0002_auto_20201215_2141'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinmodel',
            name='perpersonextrarate',
        ),
        migrations.AlterField(
            model_name='checkinmodel',
            name='chintime',
            field=models.TimeField(default='22:00:49'),
        ),
        migrations.AlterField(
            model_name='checkinmodel',
            name='extrarate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkinmodel',
            name='person',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='checkinmodel',
            name='totalamount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
