# Generated by Django 3.1.4 on 2020-12-15 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghouse', '0003_auto_20201215_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinmodel',
            name='perpersonextrarate',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='checkinmodel',
            name='chintime',
            field=models.TimeField(default='22:05:49'),
        ),
    ]
