# Generated by Django 3.1.4 on 2020-12-16 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghouse', '0004_auto_20201215_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkinmodel',
            name='perpersonextrarate',
        ),
        migrations.AddField(
            model_name='checkinmodel',
            name='totalextrarate',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='checkinmodel',
            name='chindate',
            field=models.DateField(default='2020-12-16'),
        ),
        migrations.AlterField(
            model_name='checkinmodel',
            name='chintime',
            field=models.TimeField(default='08:32:45'),
        ),
    ]
