# Generated by Django 3.1.4 on 2020-12-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ghouse', '0005_auto_20201216_0832'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkinmodel',
            name='totalroomtarif',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='checkinmodel',
            name='chintime',
            field=models.TimeField(default='09:33:59'),
        ),
    ]
